### PR TITLE
[NCL-2314] improved error message while bad request in cli

### PR DESCRIPTION
**Pull request by stanlyDoge**

### CODE REVIEW

**Comment by janinko** [comment]
Please improve the error message for everything, not just lookup. Also print whatever you received from the server when it's not json.

**Comment by stanlyDoge** [comment]
retest this please

**Comment by janinko** [comment]
:+1:

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by stanlyDoge** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
