### PR TITLE
Adding PNC interface for Dependency Analysis

### PR DESCRIPTION
**Pull request by thescouser89**
This is just a cleaned up PR with a single commit instead of several commits spread around as in #7.

### CODE REVIEW

**Comment by janinko** [comment]
:+1:

**Comment by jomrazek** [comment]
You can solve that dependency error as you write in mail just check that new version doesn't break something.

**Comment by jbartece** [comment]
add to whitelist

**Comment by jbartece** [comment]
retest this please

**Comment by thescouser89** [comment]
Boo jenkins did not catch the error under my test :(

**Comment by thescouser89** [comment]
retest this please

**Comment by jomrazek** [comment]
@thescouser89 You're right for now it is set to skip tests because testsuite is broken so it's testing just if it's possible to build it

**Pull request merged**
