### PR TITLE
Adding initial swagger initialization

### PR DESCRIPTION
**Pull request by thescouser89**
This should enable swagger for reports-rest. Right now we'll have to manually specify which rest class should be scanned for swagger annotations. Will add more code as the PRs for REST endpoints get merged.

### CODE REVIEW

**Comment by thescouser89** [comment]
test me please

**Comment by jomrazek** [comment]
It's throwing Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)] for me while deploying

**Comment by thescouser89** [comment]
Ok it turns out version `1.3.12` was the issue. Version `1.3.11` is fine.

I started to dig further and try to add some swagger annotations, but I have the issue where we define all the annotations on the interface, then have a class that defines the interface. Swagger doesn't like that one bit. Swagger cannot scan the annotations on the interface. So Swagger will miss information like the HTTP verb etc, unless I define the `@Path` annotation both on the interface and on the class implementing the interface.

So right now I'm blocked again. I checked PNC and they don't seem to be using the interface-implementation thing for endpoints. Maybe we could do that also? Not sure if it's worth it or not.

@jomrazek @janinko

**Comment by thescouser89** [comment]
https://github.com/swagger-api/swagger-core/issues/562

**Comment by thescouser89** [comment]
Closing it, will make another commit later.

**Pull request closed without merging**
