### PR TITLE
Migration to Eap 7.2.3

### PR DESCRIPTION
**Pull request by jbartece**
### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by jbartece** [comment]
PR job needs to be upgraded. It is expected to fail. I'll do it on Monday.

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
The Pull request PR jobs and the other deploy Jenkins jobs have been adjusted to get the correct EAP zip based if a particular commit is present or not.

**Comment by jbartece** [comment]
RH-SSO adapter upgraded to 7.3.0.GA to match the RH-SSO server version.
Removed unnecessary config options from the DA config.

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
@thescouser89 Thanks for changing the job to work with new&old code

**Comment by jbartece** [comment]
The tests are not actually executed as path to EAP folder is not passed properly in the Jenkins job. Fixing it.

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Pull request merged**
