### PR TITLE
[DA-166][DA-167][DA-169] Check if product-version, bcs and product exists

### PR DESCRIPTION
**Pull request by thescouser89**
bcs = BuildConfigurationSet

Check if the product-version, BuildConfigurationSet and product already exists
in PNC before trying to create a new one.

If there's one that already exist, use that one.

### CODE REVIEW

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
I'm not sure about this behavior. E.g. I think we cannot re-use the product version, when the product version already exists. It can differ (and probably will). 
@janinko @jomrazek What do you think about it?

**Comment by thescouser89** [comment]
Hmm I didn't know about that. What would be the current behaviour then?

**Comment by jbartece** [comment]
@thescouser89  Probably we should discuss it on a meeting.

**Comment by thescouser89** [comment]
@jbartece Totally forgot to mention this in the scrum meeting. Will mention it tomorrow!

**Comment by jomrazek** [comment]
@jbartece is there already some output if we should reuse product version?

**Comment by janinko** [comment]
@thescouser89 after the discussion, is this PR still relevant, or should it be closed?

**Comment by thescouser89** [comment]
@janinko I'll close it and create a new one.

**Pull request closed without merging**
