### PR TITLE
[DA-198] Do not stop at unselected node in Product import

### PR DESCRIPTION
**Pull request by thescouser89**
This commit is actually done by @janinko , this PR just fixes minor formatting issues found in #251

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbrazdil** [comment]
Sorry, I'll merge my PR instead :stuck_out_tongue:

**Pull request closed without merging**
