### PR TITLE
Initial commit for Swagger

### PR DESCRIPTION
**Pull request by thescouser89**
The swagger ui can be accessed from:
http://localhost:8080/reports-rest/swagger-ui/

Due to an issue with Swagger-Resteasy library not being able to read
JAXRS annotations from interfaces, we decided to remove the interface
and add those JAXRS annotations to the implemented classes instead. As
such, `Artifacts.java` is switched from an interface to a concrete
class, and `ArtifactsImpl.java` is removed. Same thing for `Root.java`.

The `pom.xml` is modified to add the swagger dependency.

The `web.xml` is modified to add the servlet that will serve the REST
documentation JSON data at
http://localhost:8080/reports-rest/rest/api-docs

The `webapp` folder now includes another folder, `swagger-ui`, that will
consume the documentation JSON data and provides a nice webview of the
REST endpoints.

Note that we are using v2.0.24 for `swagger-ui`, since the latest one
from master can't properly display the top-level list of apis available
right now.

JIRA: DA-10

### CODE REVIEW

**Comment by thescouser89** [comment]
test me please

**Comment by jomrazek** [comment]
:+1: working nice

**Comment by thescouser89** [comment]
https://github.com/project-ncl/dependency-analysis/pull/29

DA-10

**Comment by jbartece** [comment]
@thescouser89 Will it work also on OpenStack

**Comment by janinko** [comment]
:+1: looks ok

**Pull request merged**
