### PR TITLE
[DA-261] Add version number to the CLI

### PR DESCRIPTION
**Pull request by jomrazek**

### CODE REVIEW

**Comment by jomrazek** [comment]
@jbartece @jbrazdil please don't make changes in cli or parent pom until this PR is merged

**Comment by jomrazek** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
add to whitelist

**Comment by jomrazek** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
Please squash the commits. Also ``@cli.version@`` is not used anywhere.

**Comment by janinko** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
File formatting errors! :)

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by jomrazek** [comment]
-DpackCLI if you want to create new cli tools package

**Comment by jomrazek** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Pull request merged**
