### PR TITLE
[DA-72]: Solve reauthentication to Keycloak, when token expires

### PR DESCRIPTION
**Pull request by jbartece**
New interceptor is created, which solves the situation, when access token expired. When it happens,
it triggers reauthentication and force reexecution of the called method in PNC connector

PNCAuthentication class was reworked to be a bean

Integration test for PNCConnector was created

Beans.xml file in communication was fixed to support interceptors

### CODE REVIEW

**Comment by jomrazek** [comment]
:+1:

**Comment by jomrazek** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by thescouser89** [comment]
So from what I understand, we do a REST call to PNC with some access token, if the access token is invalid and/or old, PNC will complain about it. If PNC complain about authorization needed, we throw an exception. The exception gets intercepted by the interceptor (heh!) and it renews the access token, before repeating the request again.

@jbartece  Question: Will the interceptor create an infinite loop if say, we keep using invalid access token?

**Comment by thescouser89** [comment]
:+1:

**Comment by jbartece** [comment]
@thescouser89 You understand it correctly. And there is no possible infinite loop. If the connector throws exception second time, than it will be propagated to the caller

**Pull request merged**
