### PR TITLE
[DA-107] Change datastore to PostgreSQL

### PR DESCRIPTION
**Pull request by thescouser89**
Changes required in JBoss EAP 6.4:

1. Create a new PostgreSQL database called `da`

```bash
createdb da
```

2. In `jboss-eap-6.4/standalone/configuration/standalone.xml`:

- Add a new datasource:

```xml
<datasource jndi-name="java:jboss/datasources/PostgresDA" pool-name="PostgresDA" enabled="true">
    <connection-url>jdbc:postgresql://localhost:5432/da</connection-url>
    <driver>postgresql-jdbc4</driver>
    <security>
        <user-name>sa</user-name>
        <password>sa</password>
    </security>
</datasource>
```

Please change the username and password to something more appropriate.

- Add the JDBC PostgreSQL driver definition:

```xml
<driver name="postgresql-jdbc4" module="org.postgresql">
    <driver-class>org.postgresql.Driver</driver-class>
</driver>
```

3. In `<EAP_HOME>/modules/system/layers/base/org/postgresql/main`:
- Download the postgresql JDBC driver (https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc4.jar) and place it in the folder.

- Add a file named `module.xml` with content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.postgresql">
        <resources>
                <resource-root path="postgresql-9.4-1201.jdbc4.jar"/>
        </resources>
        <dependencies><module name="javax.api"/></dependencies>
</module>
```

### CODE REVIEW

**Comment by thescouser89** [comment]
If this PR is merged, I'll update the deployment page for PostgreSQL deployment with the instructions provided in the commit.

**Comment by jbartece** [comment]
@thescouser89 I'll check what version of the database and the driver is on the PNC servers.

**Comment by jbartece** [comment]
@thescouser89 uses postgresql-9.3.jar driver and PostgreSQL version 9.2.13. It's just for info

**Comment by jbartece** [comment]
@thescouser89 Could you backport it to the version-0.2.x branch a release 0.2.1?

**Comment by thescouser89** [comment]
@jbartece will do!

**Comment by thescouser89** [comment]
Backported to 0.2 branch.

**Pull request merged**
