### PR TITLE
[NCL-2048] Use two repository groups

### PR DESCRIPTION
**Pull request by janinko**
Use 'aproxGroup' repository for -redhat version finding.
Use 'aproxGroupPublic' for dependency search.

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
This needs change in the config.

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
test failed because of internal issues with indy. Please wait a few more days till we fix it. :disappointed:

**Comment by janinko** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
