### PR TITLE
Change aprox group for pom searching

### PR DESCRIPTION
**Pull request by jomrazek**

### CODE REVIEW

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jomrazek** [comment]
I need to change this, it will break tests in this state

**Comment by thescouser89** [comment]
retest this pelase

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
This will be solved by NCL-2048

**Pull request closed without merging**
