### PR TITLE
Disable swagger validator

### PR DESCRIPTION
**Pull request by jbrazdil**
As our service is behing firewall, the external validator can't see our json.

### CODE REVIEW

**Comment by thescouser89** [comment]
I built and deploy this PR, but it didn't seem to change anything for DA-209

**Comment by jbartece** [comment]
Good point Dustin. It's not fix of the DA-209, but it is a fix of an error, which was displayed in swagger. Anyway :+1:  for the fix

**Comment by thescouser89** [comment]
:+1:

**Comment by jbrazdil** [comment]
Yeah, I didn't read DA-209 as I though it was issue we found before Christmas. After I wanted to mark the issue as resolved, I saw my error and changed the title.

**Pull request merged**
