### PR TITLE
Removal of metrics module and use of org.jboss.pnc.metrics:pncmetrics…

### PR DESCRIPTION
**Pull request by vibe13**
…; added metrics to all singular /reports/ endpoint

### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

@thescouser89 @janinko @jbartece I have removed the module metrics to use existing org.jboss.pnc.metrics:pncmetrics , to avoid code duplication. Also, if https://github.com/project-ncl/pncmetrics/pull/6 will be merged, I would use here a new release of pncmetrics 1.1.3 to have also the errors metrics for the TimedMetric annotated endpoints (all the /reports/*)

### CODE REVIEW

**Comment by vibe13** [comment]
@janinko @thescouser89 Hi, I have added metrics (generic and per methodname) to the Websocket endpoint, can you please take a look? Thanks!

**Comment by janinko** [comment]
Seems there is problems with the deployments:
```
15:30:51,152 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."testsuite.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."testsuite.ear".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MetricsConfiguration with qualifiers @Default
  at injection point [UnbackedAnnotatedField] @Inject private org.jboss.pnc.pncmetrics.rest.GeneralRestMetricsFilter.metricsConfiguration
  at org.jboss.pnc.pncmetrics.rest.GeneralRestMetricsFilter.metricsConfiguration(GeneralRestMetricsFilter.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MetricsConfiguration with qualifiers @Default
  at injection point [UnbackedAnnotatedField] @Inject private org.jboss.pnc.pncmetrics.rest.TimedMetricFilter.metricsConfiguration
  at org.jboss.pnc.pncmetrics.rest.TimedMetricFilter.metricsConfiguration(TimedMetricFilter.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

	at org.jboss.weld.bootstrap.ConcurrentValidator.validateBeans(ConcurrentValidator.java:69)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:462)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:478)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:96)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
	... 3 more
	Suppressed: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MetricsConfiguration with qualifiers @Default
  at injection point [UnbackedAnnotatedField] @Inject private org.jboss.pnc.pncmetrics.rest.GeneralRestMetricsFilter.metricsConfiguration
  at org.jboss.pnc.pncmetrics.rest.GeneralRestMetricsFilter.metricsConfiguration(GeneralRestMetricsFilter.java:0)

		at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
		at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
		at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
		at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
		at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
		at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
		at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
		at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
		at org.jboss.threads.JBossThread.run(JBossThread.java:320)
	Suppressed: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MetricsConfiguration with qualifiers @Default
  at injection point [UnbackedAnnotatedField] @Inject private org.jboss.pnc.pncmetrics.rest.TimedMetricFilter.metricsConfiguration
  at org.jboss.pnc.pncmetrics.rest.TimedMetricFilter.metricsConfiguration(TimedMetricFilter.java:0)

		at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
		at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
		at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
		at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
		at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
		at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
		at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
		at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
		at org.jboss.threads.JBossThread.run(JBossThread.java:320)
```

**Comment by vibe13** [comment]
@janinko yep looking into it

**Comment by thescouser89** [comment]
Go to sleep @vibe13 !!!

**Comment by vibe13** [comment]
@thescouser89 @janinko ok looks we are all green now, and with the latest version of pncmetrics :-)

**Pull request merged**
