### PR TITLE
Fix some REST data implementation so it conforms with REST proposal

### PR DESCRIPTION
**Pull request by janinko**
Changed GAV/GA implementation so it is immutable and conforms with REST proposal.
Changed LooupReport so it conforms with REST proposal.

Added codehouse Jackson dependency in version that is in EAP 6.4

### CODE REVIEW

**Comment by janinko** [comment]
:-1:  There is one issue still

**Comment by janinko** [comment]
:-1:  I'll reimplement it again

**Comment by janinko** [comment]
Now I'm happy with it.

**Comment by jbartece** [comment]
@janinko Really nice approach! :+1: :+1:

**Comment by janinko** [comment]
rebase

**Comment by thescouser89** [comment]
:+1: tried some values in swagger-ui and seem to work well!

**Pull request merged**
