### PR TITLE
[NCL-2352] get rid of clonning

### PR DESCRIPTION
**Pull request by stanlyDoge**

### CODE REVIEW

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
Also delete cloneRepo field (and getters/setter) from the JSON (org.jboss.da.bc.model.rest.BuildConfiguration) and related places.

**Comment by stanlyDoge** [comment]
retest this please

**Comment by stanlyDoge** [comment]
retest this please

**Comment by janinko** [comment]
:+1:

**Comment by stanlyDoge** [comment]
retest this please

**Comment by stanlyDoge** [comment]
retest this please

**Comment by stanlyDoge** [comment]
retest this please

**Comment by janinko** [comment]
conflicts arose, please rebase

**Comment by janinko** [comment]
retest this please

**Pull request merged**
