### PR TITLE
Cartographer separated from Indy. Refactored communication code.

### PR DESCRIPTION
**Pull request by jsenko**

### CODE REVIEW

**Comment by jsenko** [comment]
@janinko can you pls verify this works? had problems with deploying DA on EAP/WF, are there special requirements on server setup?

**Comment by janinko** [comment]
add to whitelist

**Comment by janinko** [comment]
How to deploy DA is described in confluence in page **Deployment of the application and other services** or summarized in this update of README: https://github.com/project-ncl/dependency-analysis/pull/344

So this build can pass, we need tu update the job with the new configuration.

**Comment by thescouser89** [comment]
Noted!

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by thescouser89** [comment]
Yeah we are now using branch 1.0.x for Indy...

**Comment by janinko** [comment]
retest this please

**Comment by jsenko** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by jsenko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
