### PR TITLE
ditch usage of Exception, use CommunicationException instead

### PR DESCRIPTION
**Pull request by janinko**
Resteasy methods get/post/delete/... throws Exception. We just rethrowed it.
Now we package it into CommunicationException instead.

### CODE REVIEW

**Comment by jbartece** [comment]
retest this please

**Comment by thescouser89** [comment]
OMG that's a big diff! :+1:

**Comment by thescouser89** [comment]
Woops doesn't merge anymore. Sorry @janinko :worried:

**Comment by jbartece** [comment]
:+1:

**Comment by janinko** [comment]
rebased

**Pull request merged**
