### PR TITLE
Change aprox config to use DA group

### PR DESCRIPTION
**Pull request by jomrazek**
you need to change da-config according to document

https://docs.engineering.redhat.com/display/JP/Deployment+of+the+application+and+other+services

### CODE REVIEW

**Comment by jbrazdil** [comment]
:+1:

**Comment by jbrazdil** [comment]
The Jenkins jobs need to be changed.

**Comment by jomrazek** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Pull request merged**
