### PR TITLE
DA-255 Add alignemnt reports to the CLI

### PR DESCRIPTION
**Pull request by jbrazdil**

### CODE REVIEW

**Comment by janinko** [comment]
I like this change, good work @jbrazdil :sunglasses:

**Comment by thescouser89** [comment]
@janinko @jbrazdil You guys should be friends.

**Comment by thescouser89** [comment]
I'll try to find out what's going on with our silly bot.

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
@thescouser89 Did you take a look at the PR? Can I merge it?

**Comment by thescouser89** [comment]
It fails for me.

```bash
➜  cli git:(d1202ca) ✗ ./da-cli.sh align-report http://github.com/dependency-analysis.git master ./application/pom.xml                       
{ 'scmUrl': 'http://github.com/dependency-analysis.git', 'revision': 'master', 'pomPath': '', 'searchUnknownProducts': 'false', 'products': [], 'additionalRepos': [] }
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pretty.py", line 171, in reportAlign
    data = readInput()
  File "pretty.py", line 140, in readInput
    return json.loads(data)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

## Server logs
```
0:33:13,010 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (http-/127.0.0.1:8080-79) RESTEASY000210: Application.getClasses() returned unknown class type: org.jboss.da.rest.SwaggerConfiguration
20:33:25,254 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (http-/127.0.0.1:8080-80) RESTEASY000100: Failed executing POST /reports/align: org.jboss.resteasy.spi.ReaderException: org.codehaus.jackson.JsonParseException: Unexpected character (''' (code 39)): was expecting double-quote to start field name
 at [Source: org.jboss.resteasy.core.interception.MessageBodyReaderContextImpl$InputStreamWrapper@2b5dbed5; line: 1, column: 4]
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:201) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:137) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:160) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:541) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:523) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:125) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]

```

**Comment by janinko** [comment]
Two things:
 1) fixed
 2) you have error in the repo url, you are missing ``project-ncl/``

**Comment by thescouser89** [comment]
@janinko I am stupid. I should have verified my git link. Will give a thumbs up once I can run it on my machine :)

**Comment by thescouser89** [comment]
It works now! From the logs, it seems it doesn't capture the pom path though?
```
➜  cli git:(7681338) ✗ ./da-cli.sh align-report http://github.com/project-ncl/dependency-analysis.git master ./application/pom.xml
{ "scmUrl": "http://github.com/project-ncl/dependency-analysis.git", "revision": "master", "pomPath": "", "searchUnknownProducts": false, "products": [], "additionalRepos": [] }
```

On another note, looks like you forgot to remove a debug line in `listings.sh`, line 3

**Comment by janinko** [comment]
Thanks @thescouser89, pom path fixed, debug lines removed.

**Comment by jbartece** [comment]
@janinko @thescouser89 OK, it looks like all comments were anwered/fixed. CI doesn't test CLI any more. Merging...

**Pull request merged**
