### PR TITLE
[DA-187] Fix not running BC test

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
Looks good to me :+1:

**Comment by jomrazek** [comment]
Correct me if I'm wrong but you need to add bcErrors field to jsons too. It isn't set to be optional. am I wrong?

**Comment by jbartece** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by jbrazdil** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbrazdil** [comment]
just review, do not merge. I'll squash it when merging

**Comment by jbartece** [comment]
retest this please

**Comment by jbrazdil** [comment]
retest this please

**Comment by jbrazdil** [comment]
retest this please

**Comment by jbrazdil** [comment]
retest this please

**Comment by jbrazdil** [comment]
Yucheeey!! :tada:

**Comment by jbrazdil** [comment]
some changes squashed, redy to merge

**Comment by jbartece** [comment]
:+1:

**Pull request merged**
