### PR TITLE
[DA-36] implement REST data model for DA reports

### PR DESCRIPTION
**Pull request by janinko**
As described on **REST endpoints proposal** page.

### CODE REVIEW

**Comment by thescouser89** [comment]
I *love* lombok but my IDE always get confused with it :(

Should we be using lombok or should we generate those boring getters and setters to make our IDEs happy?

**Comment by rnc** [comment]
@thescouser89 Does https://github.com/mplushnikov/lombok-intellij-plugin work?

**Comment by jomrazek** [comment]
+1

**Comment by janinko** [comment]
@thescouser89 it should be possible to install the plugin from IDE, somehow.

**Comment by thescouser89** [comment]
Thanks for the plugin! Should make my IDE happy now! (How did you know I use intellij?)

**Comment by janinko** [comment]
@thescouser89 I know it because of https://github.com/thescouser89/dependency-analysis/commit/b684fd840d70ea35b3a25b6d50a826f8f6e8341d#diff-a084b794bc0759e7a6b77810e01874f2R8 :wink:

**Pull request merged**
