### PR TITLE
[DA-215] Use default module group class

### PR DESCRIPTION
**Pull request by thescouser89**
This will have the advantage that when new groups are added, the parsing
of the config json won't be broken

Stolen from @janinko :)

### CODE REVIEW

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
You thief!! :+1:

**Comment by thescouser89** [comment]
retest this please

**Pull request merged**
