### PR TITLE
Create SCM interface for cached SCM clonning

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by thescouser89** [comment]
:+1:

**Comment by jbartece** [comment]
:+1:

**Comment by janinko** [comment]
retest this please

**Comment by jomrazek** [comment]
:+1:

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by janinko** [comment]
can you re-review this? I implemented the SCM interface

**Comment by jbartece** [comment]
:+1:

**Pull request merged**
