### PR TITLE
blacklisting -redhat- artifacts

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by janinko** [comment]
add to whitelist

**Comment by michalszynkiewicz** [comment]
I don't see any "unexpected" failures...

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
We're down to one error now, let's retest this please once more!

**Pull request merged**
