### PR TITLE
Split BC and Reports model into separate modules

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by janinko** [comment]
We need this so we can easily create java client for DA (NCL-1824)

**Comment by jomrazek** [comment]
:neutral_face:

**Comment by janinko** [comment]
retest this please

**Comment by jbartece** [comment]
:+1:

**Comment by thescouser89** [comment]
Looks like some testsuite issues:

```
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS018746: Sub deployment reports-model.jar in jboss-deployment-structure.xml was not found. Available sub deployments: common.jar, testsuite.jar, bc-backend.jar, bc-rest.war, source-code-manager.jar, communication.jar, reports-backend.jar, reports-rest.war
```

**Comment by thescouser89** [comment]
By adding this patch, it seems to fix the issue:

```
diff --git a/testsuite/src/test/resources/META-INF/application.xml b/testsuite/src/test/resources/META-INF/application.xml
index 2a18b5b..fbc25e9 100644
--- a/testsuite/src/test/resources/META-INF/application.xml
+++ b/testsuite/src/test/resources/META-INF/application.xml
@@ -17,6 +17,12 @@
         <ejb>source-code-manager.jar</ejb>
     </module>
     <module>
+        <ejb>reports-model.jar</ejb>
+    </module>
+    <module>
+        <ejb>bc-model.jar</ejb>
+    </module>
+    <module>
         <ejb>reports-backend.jar</ejb>
     </module>
     <module>
```

**Comment by janinko** [comment]
Thanks @thescouser89, that hit the spot!

**Pull request merged**
