### PR TITLE
Clean and improve code

### PR DESCRIPTION
**Pull request by jbrazdil**

### CODE REVIEW

**Comment by jomrazek** [comment]
:+1:

**Comment by jomrazek** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
