### PR TITLE
[DA-144] Implement dynamic loading of remote repositories

### PR DESCRIPTION
**Pull request by jomrazek**

### CODE REVIEW

**Comment by jomrazek** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by jomrazek** [comment]
retest this please

**Comment by jbartece** [comment]
By the REST conventions the URL should be probably /repositories
and I would propose to refactor the /repositories endpoints to the single class and to move it to the same level as reports.
So, it would be:
/reports/*
/repositories/*

**Comment by jomrazek** [comment]
we was talking that we add these endpoints to reports but np i'll change it

**Comment by jbartece** [comment]
:+1:

**Pull request merged**
