### PR TITLE
[DA-59] Remove GAVs from the black/white lists

### PR DESCRIPTION
**Pull request by jomrazek**

### CODE REVIEW

**Comment by jbartece** [comment]
add to whitelist

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by jbartece** [comment]
retest this please

**Comment by janinko** [comment]
:+1:

**Pull request merged**
